var annotated =
[
    [ "AL", null, [
      [ "usdmaya", null, [
        [ "cmds", null, [
          [ "ActivatePrim", "classAL_1_1usdmaya_1_1cmds_1_1ActivatePrim.html", "classAL_1_1usdmaya_1_1cmds_1_1ActivatePrim" ],
          [ "BaseCallbackCommand", "structAL_1_1usdmaya_1_1cmds_1_1BaseCallbackCommand.html", "structAL_1_1usdmaya_1_1cmds_1_1BaseCallbackCommand" ],
          [ "Callback", "classAL_1_1usdmaya_1_1cmds_1_1Callback.html", "classAL_1_1usdmaya_1_1cmds_1_1Callback" ],
          [ "CallbackQuery", "classAL_1_1usdmaya_1_1cmds_1_1CallbackQuery.html", "classAL_1_1usdmaya_1_1cmds_1_1CallbackQuery" ],
          [ "ChangeVariant", "classAL_1_1usdmaya_1_1cmds_1_1ChangeVariant.html", "classAL_1_1usdmaya_1_1cmds_1_1ChangeVariant" ],
          [ "CreateUsdPrim", "classAL_1_1usdmaya_1_1cmds_1_1CreateUsdPrim.html", "classAL_1_1usdmaya_1_1cmds_1_1CreateUsdPrim" ],
          [ "DeleteCallbacks", "classAL_1_1usdmaya_1_1cmds_1_1DeleteCallbacks.html", "classAL_1_1usdmaya_1_1cmds_1_1DeleteCallbacks" ],
          [ "Event", "classAL_1_1usdmaya_1_1cmds_1_1Event.html", "classAL_1_1usdmaya_1_1cmds_1_1Event" ],
          [ "EventLookup", "classAL_1_1usdmaya_1_1cmds_1_1EventLookup.html", "classAL_1_1usdmaya_1_1cmds_1_1EventLookup" ],
          [ "EventQuery", "classAL_1_1usdmaya_1_1cmds_1_1EventQuery.html", "classAL_1_1usdmaya_1_1cmds_1_1EventQuery" ],
          [ "InternalProxyShapeSelect", "classAL_1_1usdmaya_1_1cmds_1_1InternalProxyShapeSelect.html", "classAL_1_1usdmaya_1_1cmds_1_1InternalProxyShapeSelect" ],
          [ "LayerCommandBase", "classAL_1_1usdmaya_1_1cmds_1_1LayerCommandBase.html", "classAL_1_1usdmaya_1_1cmds_1_1LayerCommandBase" ],
          [ "LayerCreateLayer", "classAL_1_1usdmaya_1_1cmds_1_1LayerCreateLayer.html", "classAL_1_1usdmaya_1_1cmds_1_1LayerCreateLayer" ],
          [ "LayerCurrentEditTarget", "classAL_1_1usdmaya_1_1cmds_1_1LayerCurrentEditTarget.html", "classAL_1_1usdmaya_1_1cmds_1_1LayerCurrentEditTarget" ],
          [ "LayerExport", "classAL_1_1usdmaya_1_1cmds_1_1LayerExport.html", "classAL_1_1usdmaya_1_1cmds_1_1LayerExport" ],
          [ "LayerGetLayers", "classAL_1_1usdmaya_1_1cmds_1_1LayerGetLayers.html", "classAL_1_1usdmaya_1_1cmds_1_1LayerGetLayers" ],
          [ "LayerManager", "classAL_1_1usdmaya_1_1cmds_1_1LayerManager.html", "classAL_1_1usdmaya_1_1cmds_1_1LayerManager" ],
          [ "LayerSave", "classAL_1_1usdmaya_1_1cmds_1_1LayerSave.html", "classAL_1_1usdmaya_1_1cmds_1_1LayerSave" ],
          [ "LayerSetMuted", "classAL_1_1usdmaya_1_1cmds_1_1LayerSetMuted.html", "classAL_1_1usdmaya_1_1cmds_1_1LayerSetMuted" ],
          [ "ListCallbacks", "classAL_1_1usdmaya_1_1cmds_1_1ListCallbacks.html", "classAL_1_1usdmaya_1_1cmds_1_1ListCallbacks" ],
          [ "ListEvents", "classAL_1_1usdmaya_1_1cmds_1_1ListEvents.html", "classAL_1_1usdmaya_1_1cmds_1_1ListEvents" ],
          [ "ManageRenderer", "classAL_1_1usdmaya_1_1cmds_1_1ManageRenderer.html", "classAL_1_1usdmaya_1_1cmds_1_1ManageRenderer" ],
          [ "ProxyShapeCommandBase", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapeCommandBase.html", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapeCommandBase" ],
          [ "ProxyShapeFindLoadable", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapeFindLoadable.html", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapeFindLoadable" ],
          [ "ProxyShapeImport", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapeImport.html", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapeImport" ],
          [ "ProxyShapeImportAllTransforms", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapeImportAllTransforms.html", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapeImportAllTransforms" ],
          [ "ProxyShapeImportPrimPathAsMaya", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapeImportPrimPathAsMaya.html", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapeImportPrimPathAsMaya" ],
          [ "ProxyShapePostLoadProcess", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapePostLoadProcess.html", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapePostLoadProcess" ],
          [ "ProxyShapePostSelect", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapePostSelect.html", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapePostSelect" ],
          [ "ProxyShapePrintRefCountState", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapePrintRefCountState.html", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapePrintRefCountState" ],
          [ "ProxyShapeRemoveAllTransforms", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapeRemoveAllTransforms.html", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapeRemoveAllTransforms" ],
          [ "ProxyShapeResync", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapeResync.html", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapeResync" ],
          [ "ProxyShapeSelect", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapeSelect.html", "classAL_1_1usdmaya_1_1cmds_1_1ProxyShapeSelect" ],
          [ "TranslatePrim", "classAL_1_1usdmaya_1_1cmds_1_1TranslatePrim.html", "classAL_1_1usdmaya_1_1cmds_1_1TranslatePrim" ],
          [ "TriggerEvent", "classAL_1_1usdmaya_1_1cmds_1_1TriggerEvent.html", "classAL_1_1usdmaya_1_1cmds_1_1TriggerEvent" ],
          [ "UsdDebugCommand", "classAL_1_1usdmaya_1_1cmds_1_1UsdDebugCommand.html", "classAL_1_1usdmaya_1_1cmds_1_1UsdDebugCommand" ]
        ] ],
        [ "fileio", null, [
          [ "translators", null, [
            [ "DagNodeTranslator", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1DagNodeTranslator.html", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1DagNodeTranslator" ],
            [ "DgNodeTranslator", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1DgNodeTranslator.html", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1DgNodeTranslator" ],
            [ "TransformTranslator", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1TransformTranslator.html", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1TransformTranslator" ],
            [ "TranslatorAbstract", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorAbstract.html", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorAbstract" ],
            [ "TranslatorBase", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorBase.html", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorBase" ],
            [ "TranslatorContext", "structAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorContext.html", "structAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorContext" ],
            [ "TranslatorFactory", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorFactory.html", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorFactory" ],
            [ "TranslatorFactoryBase", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorFactoryBase.html", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorFactoryBase" ],
            [ "TranslatorManufacture", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorManufacture.html", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorManufacture" ],
            [ "TranslatorParameters", "structAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorParameters.html", "structAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorParameters" ],
            [ "TranslatorTestPlugin", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorTestPlugin.html", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorTestPlugin" ],
            [ "TranslatorTestType", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorTestType.html", "classAL_1_1usdmaya_1_1fileio_1_1translators_1_1TranslatorTestType" ]
          ] ],
          [ "AnimationCheckTransformAttributes", "classAL_1_1usdmaya_1_1fileio_1_1AnimationCheckTransformAttributes.html", "classAL_1_1usdmaya_1_1fileio_1_1AnimationCheckTransformAttributes" ],
          [ "AnimationTranslator", "classAL_1_1usdmaya_1_1fileio_1_1AnimationTranslator.html", "classAL_1_1usdmaya_1_1fileio_1_1AnimationTranslator" ],
          [ "Export", "classAL_1_1usdmaya_1_1fileio_1_1Export.html", "classAL_1_1usdmaya_1_1fileio_1_1Export" ],
          [ "ExportCommand", "classAL_1_1usdmaya_1_1fileio_1_1ExportCommand.html", "classAL_1_1usdmaya_1_1fileio_1_1ExportCommand" ],
          [ "ExporterParams", "structAL_1_1usdmaya_1_1fileio_1_1ExporterParams.html", "structAL_1_1usdmaya_1_1fileio_1_1ExporterParams" ],
          [ "Import", "classAL_1_1usdmaya_1_1fileio_1_1Import.html", "classAL_1_1usdmaya_1_1fileio_1_1Import" ],
          [ "ImportCommand", "classAL_1_1usdmaya_1_1fileio_1_1ImportCommand.html", "classAL_1_1usdmaya_1_1fileio_1_1ImportCommand" ],
          [ "ImporterParams", "structAL_1_1usdmaya_1_1fileio_1_1ImporterParams.html", "structAL_1_1usdmaya_1_1fileio_1_1ImporterParams" ],
          [ "NodeFactory", "structAL_1_1usdmaya_1_1fileio_1_1NodeFactory.html", "structAL_1_1usdmaya_1_1fileio_1_1NodeFactory" ],
          [ "ScaledPair", "structAL_1_1usdmaya_1_1fileio_1_1ScaledPair.html", "structAL_1_1usdmaya_1_1fileio_1_1ScaledPair" ],
          [ "SchemaPrimsUtils", "classAL_1_1usdmaya_1_1fileio_1_1SchemaPrimsUtils.html", "classAL_1_1usdmaya_1_1fileio_1_1SchemaPrimsUtils" ],
          [ "TransformIterator", "classAL_1_1usdmaya_1_1fileio_1_1TransformIterator.html", "classAL_1_1usdmaya_1_1fileio_1_1TransformIterator" ]
        ] ],
        [ "nodes", null, [
          [ "proxy", null, [
            [ "DrivenTransforms", "classAL_1_1usdmaya_1_1nodes_1_1proxy_1_1DrivenTransforms.html", "classAL_1_1usdmaya_1_1nodes_1_1proxy_1_1DrivenTransforms" ],
            [ "PrimFilter", "classAL_1_1usdmaya_1_1nodes_1_1proxy_1_1PrimFilter.html", "classAL_1_1usdmaya_1_1nodes_1_1proxy_1_1PrimFilter" ],
            [ "PrimFilterInterface", "structAL_1_1usdmaya_1_1nodes_1_1proxy_1_1PrimFilterInterface.html", "structAL_1_1usdmaya_1_1nodes_1_1proxy_1_1PrimFilterInterface" ]
          ] ],
          [ "DirtyOnlyIterator", "classAL_1_1usdmaya_1_1nodes_1_1DirtyOnlyIterator.html", "classAL_1_1usdmaya_1_1nodes_1_1DirtyOnlyIterator" ],
          [ "FindLockedPrimsLogic", "structAL_1_1usdmaya_1_1nodes_1_1FindLockedPrimsLogic.html", null ],
          [ "FindUnselectablePrimsLogic", "structAL_1_1usdmaya_1_1nodes_1_1FindUnselectablePrimsLogic.html", "structAL_1_1usdmaya_1_1nodes_1_1FindUnselectablePrimsLogic" ],
          [ "HierarchyIterationLogic", "structAL_1_1usdmaya_1_1nodes_1_1HierarchyIterationLogic.html", "structAL_1_1usdmaya_1_1nodes_1_1HierarchyIterationLogic" ],
          [ "Layer", "classAL_1_1usdmaya_1_1nodes_1_1Layer.html", "classAL_1_1usdmaya_1_1nodes_1_1Layer" ],
          [ "LayerDatabase", "classAL_1_1usdmaya_1_1nodes_1_1LayerDatabase.html", "classAL_1_1usdmaya_1_1nodes_1_1LayerDatabase" ],
          [ "LayerManager", "classAL_1_1usdmaya_1_1nodes_1_1LayerManager.html", "classAL_1_1usdmaya_1_1nodes_1_1LayerManager" ],
          [ "ProxyDrawOverride", "classAL_1_1usdmaya_1_1nodes_1_1ProxyDrawOverride.html", "classAL_1_1usdmaya_1_1nodes_1_1ProxyDrawOverride" ],
          [ "ProxyShape", "classAL_1_1usdmaya_1_1nodes_1_1ProxyShape.html", "classAL_1_1usdmaya_1_1nodes_1_1ProxyShape" ],
          [ "ProxyShapeUI", "classAL_1_1usdmaya_1_1nodes_1_1ProxyShapeUI.html", "classAL_1_1usdmaya_1_1nodes_1_1ProxyShapeUI" ],
          [ "RendererManager", "classAL_1_1usdmaya_1_1nodes_1_1RendererManager.html", "classAL_1_1usdmaya_1_1nodes_1_1RendererManager" ],
          [ "SelectionList", "classAL_1_1usdmaya_1_1nodes_1_1SelectionList.html", "classAL_1_1usdmaya_1_1nodes_1_1SelectionList" ],
          [ "SelectionUndoHelper", "structAL_1_1usdmaya_1_1nodes_1_1SelectionUndoHelper.html", "structAL_1_1usdmaya_1_1nodes_1_1SelectionUndoHelper" ],
          [ "Transform", "classAL_1_1usdmaya_1_1nodes_1_1Transform.html", "classAL_1_1usdmaya_1_1nodes_1_1Transform" ],
          [ "TransformationMatrix", "classAL_1_1usdmaya_1_1nodes_1_1TransformationMatrix.html", "classAL_1_1usdmaya_1_1nodes_1_1TransformationMatrix" ]
        ] ],
        [ "DrivenTransformsData", "classAL_1_1usdmaya_1_1DrivenTransformsData.html", "classAL_1_1usdmaya_1_1DrivenTransformsData" ],
        [ "Global", "classAL_1_1usdmaya_1_1Global.html", null ],
        [ "Metadata", "structAL_1_1usdmaya_1_1Metadata.html", null ],
        [ "Profiler", "classAL_1_1usdmaya_1_1Profiler.html", null ],
        [ "ProfilerSectionPath", "classAL_1_1usdmaya_1_1ProfilerSectionPath.html", "classAL_1_1usdmaya_1_1ProfilerSectionPath" ],
        [ "ProfilerSectionTag", "classAL_1_1usdmaya_1_1ProfilerSectionTag.html", "classAL_1_1usdmaya_1_1ProfilerSectionTag" ],
        [ "SelectabilityDB", "classAL_1_1usdmaya_1_1SelectabilityDB.html", "classAL_1_1usdmaya_1_1SelectabilityDB" ],
        [ "StageCache", "classAL_1_1usdmaya_1_1StageCache.html", null ],
        [ "StageData", "classAL_1_1usdmaya_1_1StageData.html", "classAL_1_1usdmaya_1_1StageData" ]
      ] ]
    ] ],
    [ "std", null, [
      [ "hash< AL::usdmaya::ProfilerSectionPath >", "structstd_1_1hash_3_01AL_1_1usdmaya_1_1ProfilerSectionPath_01_4.html", "structstd_1_1hash_3_01AL_1_1usdmaya_1_1ProfilerSectionPath_01_4" ],
      [ "hash< AL::usdmaya::ProfilerSectionTag >", "structstd_1_1hash_3_01AL_1_1usdmaya_1_1ProfilerSectionTag_01_4.html", "structstd_1_1hash_3_01AL_1_1usdmaya_1_1ProfilerSectionTag_01_4" ]
    ] ],
    [ "compare_MDagPath", "structcompare__MDagPath.html", "structcompare__MDagPath" ],
    [ "compare_MPlug", "structcompare__MPlug.html", "structcompare__MPlug" ]
];